###############################################################################
# @generated
# DO NOT MODIFY: This file is auto-generated by a crate_universe tool. To
# regenerate this file, run the following:
#
#     bazel run @@//vendor_local_pkgs:crates_vendor
###############################################################################
"""
# `crates_repository` API

- [aliases](#aliases)
- [crate_deps](#crate_deps)
- [all_crate_deps](#all_crate_deps)
- [crate_repositories](#crate_repositories)

"""

load("@bazel_skylib//lib:selects.bzl", "selects")

###############################################################################
# MACROS API
###############################################################################

# An identifier that represent common dependencies (unconditional).
_COMMON_CONDITION = ""

# An identifier that represents a requried feature (unconditional).
_REQUIRED_FEATURE = ""

def _flatten_features(features, enabled_features):
    """
    Flatten features of a crate

    Args:
        features (dict): A map of feature to list of other features
        enabled_features (list): A list of enabled features

    Returns:
        set: A set of all enabled features
    """
    resolved = set()
    queue = list(enabled_features)

    for _ in range(10000):
        if len(queue) == 0:
            break

        feat = queue.pop()
        if feat in resolved:
            continue

        if feat not in features:
            fail("{} is not apart of the features for this package".format(feat))

        resolved.add(feat)
        queue.extend(features[feat])

    return resolved

def _flatten_dependency_maps(all_dependency_maps, enabled_features_map):
    """Flatten a list of dependency maps into one dictionary.

    Dependency maps have the following structure:

    ```python
    DEPENDENCIES_MAP = {
        # The first key in the map is a feature flag
        "feature": {
            # Not all dependencies are supported for all platforms.
            # the condition key is the condition required to be true
            # on the host platform.
            "condition": {

                # An alias to a crate target.     # The label of the crate target the
                # Aliases are only crate names.   # package name refers to.
                "package_name":                   "@full//:label",
            }
        }
    }
    ```

    Args:
        all_dependency_maps (list): A list of dicts as described above
        enabled_features_map (list): A list of enabled features

    Returns:
        dict: A dictionary as described above
    """
    dependencies = {}
    feature_conditions = {
        _COMMON_CONDITION: set(enabled_features_map.get(_COMMON_CONDITION, set())),
    }

    for condition, feature in enabled_features_map.items():
        for condition in _CONDITIONS.get(condition, []):
            feature_conditions.setdefault(condition, set()).update(feature)

    for feature_deps_map in all_dependency_maps:
        for feature, conditional_deps_map in feature_deps_map.items():
            for condition, deps_map in conditional_deps_map.items():
                condition_flags = _CONDITIONS[condition] if condition != _COMMON_CONDITION else feature_conditions.keys()
                for condition in condition_flags:
                    if feature == _REQUIRED_FEATURE or feature in feature_conditions.get(_COMMON_CONDITION, set()) or feature in feature_conditions.get(condition, set()):
                        dependencies.setdefault(condition, dict()).update(deps_map)

    if _COMMON_CONDITION in dependencies:
        for cond, v in dependencies.items():
            if cond != _COMMON_CONDITION:
                for k in dependencies[_COMMON_CONDITION]:
                    v.pop(k, default = None)

    return dependencies

def _make_crate_features(package_name = None):
    if package_name == None:
        package_name = native.package_name()

    conditions = {}
    vtable = {}

    def make_set():
        return struct(
            _type = "FeatureMap",
            conditions = conditions,
            **vtable
        )

    def feature_map_add(other):
        if other:
            type_other = type(other)
            if type_other == "list" or type_other == "set":
                conditions.setdefault(_COMMON_CONDITION, set()).update(other)
            elif type_other == "dict":
                for key, value in other.items():
                    conditions.setdefault(key, set()).update(value)
            elif hasattr(other, "_type") and other._type == "FeatureMap":
                for key, value in other.conditions.items():
                    conditions.setdefault(key, set()).update(value)
            else:
                fail("unsupported add operation between FeatureMap and %s" % type_other)

        return make_set()

    def feature_map_flatten():
        for features in conditions.values():
            features.update(_flatten_features(_FEATURE_FLAGS.get(package_name, []), features))

        return make_set()

    def feature_map_select():
        feature_map_flatten()
        features = []
        for condition, deps in conditions.items():
            if condition == _COMMON_CONDITION:
                features += list(deps)
            else:
                features += selects.with_or({
                    tuple(_CONDITIONS[condition]): list(deps),
                    "//conditions:default": [],
                })
        return features

    def feature_map_get(condition, default = None):
        return conditions.get(condition, default)

    def feature_map_items():
        return conditions.items()

    vtable["add"] = feature_map_add
    vtable["select"] = feature_map_select
    vtable["flatten"] = feature_map_flatten
    vtable["get"] = feature_map_get
    vtable["items"] = feature_map_items

    return make_set()

def crate_features(
        all = False,
        additional = None,
        default = True,
        package_name = None):
    """Resolves the features for a crate

    Args:
        all (bool, optional): If we should include all crate features.
        additional (list, optional): The desired list of crate targets.
        default: (bool, optional): Should we include the default resolved features.
        package_name (str, optional): The package name of the set of dependencies to look up.
            Defaults to `native.package_name()`.

    Returns:
        list: a map of features based on some conditions
    """

    if package_name == None:
        package_name = native.package_name()

    features = _make_crate_features().add(additional)

    if all:
        features.add(_FEATURE_FLAGS.get(package_name, {}).keys())

    if default:
        features.add(_RESOLVED_FEATURE_FLAGS.get(package_name, {}))

    return features

def crate_deps(deps, package_name = None):
    """Finds the fully qualified label of the requested crates for the package where this macro is called.

    Args:
        deps (list): The desired list of crate targets.
        package_name (str, optional): The package name of the set of dependencies to look up.
            Defaults to `native.package_name()`.

    Returns:
        list: A list of labels to generated rust targets (str)
    """

    if not deps:
        return []

    if package_name == None:
        package_name = native.package_name()

    # Join both sets of dependencies
    dependencies = _flatten_dependency_maps([
        _NORMAL_DEPENDENCIES.get(package_name, {}),
        _NORMAL_DEV_DEPENDENCIES.get(package_name, {}),
        _PROC_MACRO_DEPENDENCIES.get(package_name, {}),
        _PROC_MACRO_DEV_DEPENDENCIES.get(package_name, {}),
        _BUILD_DEPENDENCIES.get(package_name, {}),
        _BUILD_PROC_MACRO_DEPENDENCIES.get(package_name, {}),
    ], crate_features(package_name = package_name, all = True).flatten())

    # Combine all conditional packages so we can easily index over a flat list
    # TODO: Perhaps this should actually return select statements and maintain
    # the conditionals of the dependencies
    flat_deps = {}
    for deps_set in dependencies.values():
        for crate_name, crate_label in deps_set.items():
            flat_deps.update({crate_name: crate_label})

    missing_crates = []
    crate_targets = []
    for crate_target in deps:
        if crate_target not in flat_deps:
            missing_crates.append(crate_target)
        else:
            crate_targets.append(flat_deps[crate_target])

    if missing_crates:
        fail("Could not find crates `{}` among dependencies of `{}`. Available dependencies were `{}`".format(
            missing_crates,
            package_name,
            dependencies,
        ))

    return crate_targets

def all_crate_deps(
        normal = False,
        normal_dev = False,
        proc_macro = False,
        proc_macro_dev = False,
        build = False,
        build_proc_macro = False,
        features = None,
        package_name = None):
    """Finds the fully qualified label of all requested direct crate dependencies \
    for the package where this macro is called.

    If no parameters are set, all normal dependencies are returned. Setting any one flag will
    otherwise impact the contents of the returned list.

    Args:
        normal (bool, optional): If True, normal dependencies are included in the
            output list.
        normal_dev (bool, optional): If True, normal dev dependencies will be
            included in the output list..
        proc_macro (bool, optional): If True, proc_macro dependencies are included
            in the output list.
        proc_macro_dev (bool, optional): If True, dev proc_macro dependencies are
            included in the output list.
        build (bool, optional): If True, build dependencies are included
            in the output list.
        build_proc_macro (bool, optional): If True, build proc_macro dependencies are
            included in the output list.
        features ([str], optional): A list of additional features to include when
            finding crate dependencies.
        package_name (str, optional): The package name of the set of dependencies to look up.
            Defaults to `native.package_name()` when unset.

    Returns:
        list: A list of labels to generated rust targets (str)
    """

    if package_name == None:
        package_name = native.package_name()

    if features == None:
        features = crate_features(package_name = package_name)

    # Default to always using normal dependencies
    if not (normal or normal_dev or proc_macro or proc_macro_dev or build or build_proc_macro):
        normal = True

    # Determine the relevant maps to use
    all_dependency_maps = []
    if normal and package_name in _NORMAL_DEPENDENCIES:
        all_dependency_maps.append(_NORMAL_DEPENDENCIES.get(package_name, {}))
    if normal_dev and package_name in _NORMAL_DEV_DEPENDENCIES:
        all_dependency_maps.append(_NORMAL_DEV_DEPENDENCIES.get(package_name, {}))
    if proc_macro and package_name in _PROC_MACRO_DEPENDENCIES:
        all_dependency_maps.append(_PROC_MACRO_DEPENDENCIES.get(package_name, {}))
    if proc_macro_dev and package_name in _PROC_MACRO_DEV_DEPENDENCIES:
        all_dependency_maps.append(_PROC_MACRO_DEV_DEPENDENCIES.get(package_name, {}))
    if build and package_name in _BUILD_DEPENDENCIES:
        all_dependency_maps.append(_BUILD_DEPENDENCIES.get(package_name, {}))
    if build_proc_macro and package_name in _BUILD_PROC_MACRO_DEPENDENCIES:
        all_dependency_maps.append(_BUILD_PROC_MACRO_DEPENDENCIES.get(package_name, {}))

    if not all_dependency_maps:
        print("Tried to get all_crate_deps for package " + package_name + " but that package had no Cargo.toml file")

    features = _make_crate_features(package_name = package_name).add(features).flatten()
    dependencies = _flatten_dependency_maps(all_dependency_maps, features)

    crate_deps = list(dependencies.pop(_COMMON_CONDITION, {}).values())
    if dependencies:
        select_statement = {
            "//conditions:default": [],
        }
        for condition, deps in dependencies.items():
            select_statement[condition] = deps.values()

        crate_deps += select(select_statement)

    return crate_deps

def aliases(
        normal = False,
        normal_dev = False,
        proc_macro = False,
        proc_macro_dev = False,
        build = False,
        build_proc_macro = False,
        features = None,
        package_name = None):
    """Produces a map of Crate alias names to their original label

    If no dependency kinds are specified, `normal` and `proc_macro` are used by default.
    Setting any one flag will otherwise determine the contents of the returned dict.

    Args:
        normal (bool, optional): If True, normal dependencies are included in the
            output list.
        normal_dev (bool, optional): If True, normal dev dependencies will be
            included in the output list..
        proc_macro (bool, optional): If True, proc_macro dependencies are included
            in the output list.
        proc_macro_dev (bool, optional): If True, dev proc_macro dependencies are
            included in the output list.
        build (bool, optional): If True, build dependencies are included
            in the output list.
        build_proc_macro (bool, optional): If True, build proc_macro dependencies are
            included in the output list.
        features ([str], optional): A list of additional features to include when
            finding crate dependencies.
        package_name (str, optional): The package name of the set of dependencies to look up.
            Defaults to `native.package_name()` when unset.

    Returns:
        dict: The aliases of all associated packages
    """
    if package_name == None:
        package_name = native.package_name()

    if features == None:
        features = crate_features(package_name = package_name)

    if not (normal or normal_dev or proc_macro or proc_macro_dev or build or build_proc_macro):
        normal = True
        proc_macro = True

    # Determine the relevant maps to use
    all_aliases_maps = []
    if normal and package_name in _NORMAL_ALIASES:
        all_aliases_maps.append(_NORMAL_ALIASES.get(package_name, {}))
    if normal_dev and package_name in _NORMAL_DEV_ALIASES:
        all_aliases_maps.append(_NORMAL_DEV_ALIASES.get(package_name, {}))
    if proc_macro and package_name in _PROC_MACRO_ALIASES:
        all_aliases_maps.append(_PROC_MACRO_ALIASES.get(package_name, {}))
    if proc_macro_dev and package_name in _PROC_MACRO_DEV_ALIASES:
        all_aliases_maps.append(_PROC_MACRO_DEV_ALIASES.get(package_name, {}))
    if build and package_name in _BUILD_ALIASES:
        all_aliases_maps.append(_BUILD_ALIASES.get(package_name, {}))
    if build_proc_macro and package_name in _BUILD_PROC_MACRO_ALIASES:
        all_aliases_maps.append(_BUILD_PROC_MACRO_ALIASES.get(package_name, {}))

    if not all_aliases_maps:
        return dict()

    features = _make_crate_features(package_name = package_name).add(features).flatten()
    aliases = _flatten_dependency_maps(all_aliases_maps, features)
    common_items = aliases.pop(_COMMON_CONDITION, {}).items()

    # If there are only common items in the dictionary, immediately return them
    if not aliases:
        return dict(common_items)

    # Build a single select statement where each conditional has accounted for the
    # common set of aliases.
    crate_aliases = {"//conditions:default": dict(common_items)}
    for condition, deps in aliases.items():
        crate_aliases[condition] = dict(deps.items() + common_items)

    return select(crate_aliases)

###############################################################################
# WORKSPACE MEMBER DEPS AND ALIASES
###############################################################################

_NORMAL_DEPENDENCIES = {
    "": {
        _REQUIRED_FEATURE: {
            _COMMON_CONDITION: {
                "axum": Label("//vendor_local_pkgs/crates/axum-0.4.8:axum"),
                "hyper": Label("//vendor_local_pkgs/crates/hyper-0.14.32:hyper"),
                "mime": Label("//vendor_local_pkgs/crates/mime-0.3.17:mime"),
                "serde_json": Label("//vendor_local_pkgs/crates/serde_json-1.0.143:serde_json"),
                "socket2": Label("//vendor_local_pkgs/crates/socket2-0.4.10:socket2"),
                "tokio": Label("//vendor_local_pkgs/crates/tokio-1.47.1:tokio"),
                "tower": Label("//vendor_local_pkgs/crates/tower-0.4.13:tower"),
                "tower-http": Label("//vendor_local_pkgs/crates/tower-http-0.2.5:tower_http"),
                "tracing": Label("//vendor_local_pkgs/crates/tracing-0.1.41:tracing"),
                "tracing-subscriber": Label("//vendor_local_pkgs/crates/tracing-subscriber-0.3.20:tracing_subscriber"),
            },
        },
    },
}

_NORMAL_ALIASES = {
    "": {
        _REQUIRED_FEATURE: {
            _COMMON_CONDITION: {
            },
        },
    },
}

_NORMAL_DEV_DEPENDENCIES = {
    "": {
    },
}

_NORMAL_DEV_ALIASES = {
    "": {
    },
}

_PROC_MACRO_DEPENDENCIES = {
    "": {
    },
}

_PROC_MACRO_ALIASES = {
    "": {
    },
}

_PROC_MACRO_DEV_DEPENDENCIES = {
    "": {
    },
}

_PROC_MACRO_DEV_ALIASES = {
    "": {
    },
}

_BUILD_DEPENDENCIES = {
    "": {
    },
}

_BUILD_ALIASES = {
    "": {
    },
}

_BUILD_PROC_MACRO_DEPENDENCIES = {
    "": {
    },
}

_BUILD_PROC_MACRO_ALIASES = {
    "": {
    },
}

_FEATURE_FLAGS = {
    "": {
    },
}

_RESOLVED_FEATURE_FLAGS = {
    "": {
    },
}

_CONDITIONS = {
    "aarch64-apple-darwin": ["@rules_rust//rust/platform:aarch64-apple-darwin"],
    "aarch64-apple-ios": ["@rules_rust//rust/platform:aarch64-apple-ios"],
    "aarch64-apple-ios-sim": ["@rules_rust//rust/platform:aarch64-apple-ios-sim"],
    "aarch64-linux-android": ["@rules_rust//rust/platform:aarch64-linux-android"],
    "aarch64-pc-windows-msvc": ["@rules_rust//rust/platform:aarch64-pc-windows-msvc"],
    "aarch64-unknown-fuchsia": ["@rules_rust//rust/platform:aarch64-unknown-fuchsia"],
    "aarch64-unknown-linux-gnu": ["@rules_rust//rust/platform:aarch64-unknown-linux-gnu", "@rules_rust//rust/platform:aarch64-unknown-nixos-gnu"],
    "aarch64-unknown-nixos-gnu": ["@rules_rust//rust/platform:aarch64-unknown-nixos-gnu"],
    "aarch64-unknown-nto-qnx710": ["@rules_rust//rust/platform:aarch64-unknown-nto-qnx710"],
    "aarch64-unknown-uefi": ["@rules_rust//rust/platform:aarch64-unknown-uefi"],
    "arm-unknown-linux-gnueabi": ["@rules_rust//rust/platform:arm-unknown-linux-gnueabi"],
    "armv7-linux-androideabi": ["@rules_rust//rust/platform:armv7-linux-androideabi"],
    "armv7-unknown-linux-gnueabi": ["@rules_rust//rust/platform:armv7-unknown-linux-gnueabi"],
    "cfg(all(any(target_arch = \"x86_64\", target_arch = \"arm64ec\"), target_env = \"msvc\", not(windows_raw_dylib)))": ["@rules_rust//rust/platform:x86_64-pc-windows-msvc"],
    "cfg(all(target_arch = \"aarch64\", target_env = \"msvc\", not(windows_raw_dylib)))": ["@rules_rust//rust/platform:aarch64-pc-windows-msvc"],
    "cfg(all(target_arch = \"x86\", target_env = \"msvc\", not(windows_raw_dylib)))": ["@rules_rust//rust/platform:i686-pc-windows-msvc"],
    "cfg(not(target_family = \"wasm\"))": ["@rules_rust//rust/platform:aarch64-apple-darwin", "@rules_rust//rust/platform:aarch64-apple-ios", "@rules_rust//rust/platform:aarch64-apple-ios-sim", "@rules_rust//rust/platform:aarch64-linux-android", "@rules_rust//rust/platform:aarch64-pc-windows-msvc", "@rules_rust//rust/platform:aarch64-unknown-fuchsia", "@rules_rust//rust/platform:aarch64-unknown-linux-gnu", "@rules_rust//rust/platform:aarch64-unknown-nixos-gnu", "@rules_rust//rust/platform:aarch64-unknown-nto-qnx710", "@rules_rust//rust/platform:aarch64-unknown-uefi", "@rules_rust//rust/platform:arm-unknown-linux-gnueabi", "@rules_rust//rust/platform:armv7-linux-androideabi", "@rules_rust//rust/platform:armv7-unknown-linux-gnueabi", "@rules_rust//rust/platform:i686-apple-darwin", "@rules_rust//rust/platform:i686-linux-android", "@rules_rust//rust/platform:i686-pc-windows-msvc", "@rules_rust//rust/platform:i686-unknown-freebsd", "@rules_rust//rust/platform:i686-unknown-linux-gnu", "@rules_rust//rust/platform:powerpc-unknown-linux-gnu", "@rules_rust//rust/platform:riscv32imc-unknown-none-elf", "@rules_rust//rust/platform:riscv64gc-unknown-linux-gnu", "@rules_rust//rust/platform:riscv64gc-unknown-none-elf", "@rules_rust//rust/platform:s390x-unknown-linux-gnu", "@rules_rust//rust/platform:thumbv7em-none-eabi", "@rules_rust//rust/platform:thumbv8m.main-none-eabi", "@rules_rust//rust/platform:x86_64-apple-darwin", "@rules_rust//rust/platform:x86_64-apple-ios", "@rules_rust//rust/platform:x86_64-linux-android", "@rules_rust//rust/platform:x86_64-pc-windows-msvc", "@rules_rust//rust/platform:x86_64-unknown-freebsd", "@rules_rust//rust/platform:x86_64-unknown-fuchsia", "@rules_rust//rust/platform:x86_64-unknown-linux-gnu", "@rules_rust//rust/platform:x86_64-unknown-nixos-gnu", "@rules_rust//rust/platform:x86_64-unknown-none", "@rules_rust//rust/platform:x86_64-unknown-uefi"],
    "cfg(target_os = \"wasi\")": ["@rules_rust//rust/platform:wasm32-wasip1", "@rules_rust//rust/platform:wasm32-wasip1-threads", "@rules_rust//rust/platform:wasm32-wasip2"],
    "cfg(unix)": ["@rules_rust//rust/platform:aarch64-apple-darwin", "@rules_rust//rust/platform:aarch64-apple-ios", "@rules_rust//rust/platform:aarch64-apple-ios-sim", "@rules_rust//rust/platform:aarch64-linux-android", "@rules_rust//rust/platform:aarch64-unknown-fuchsia", "@rules_rust//rust/platform:aarch64-unknown-linux-gnu", "@rules_rust//rust/platform:aarch64-unknown-nixos-gnu", "@rules_rust//rust/platform:aarch64-unknown-nto-qnx710", "@rules_rust//rust/platform:arm-unknown-linux-gnueabi", "@rules_rust//rust/platform:armv7-linux-androideabi", "@rules_rust//rust/platform:armv7-unknown-linux-gnueabi", "@rules_rust//rust/platform:i686-apple-darwin", "@rules_rust//rust/platform:i686-linux-android", "@rules_rust//rust/platform:i686-unknown-freebsd", "@rules_rust//rust/platform:i686-unknown-linux-gnu", "@rules_rust//rust/platform:powerpc-unknown-linux-gnu", "@rules_rust//rust/platform:riscv64gc-unknown-linux-gnu", "@rules_rust//rust/platform:s390x-unknown-linux-gnu", "@rules_rust//rust/platform:wasm32-unknown-emscripten", "@rules_rust//rust/platform:x86_64-apple-darwin", "@rules_rust//rust/platform:x86_64-apple-ios", "@rules_rust//rust/platform:x86_64-linux-android", "@rules_rust//rust/platform:x86_64-unknown-freebsd", "@rules_rust//rust/platform:x86_64-unknown-fuchsia", "@rules_rust//rust/platform:x86_64-unknown-linux-gnu", "@rules_rust//rust/platform:x86_64-unknown-nixos-gnu"],
    "cfg(windows)": ["@rules_rust//rust/platform:aarch64-pc-windows-msvc", "@rules_rust//rust/platform:i686-pc-windows-msvc", "@rules_rust//rust/platform:x86_64-pc-windows-msvc"],
    "i686-apple-darwin": ["@rules_rust//rust/platform:i686-apple-darwin"],
    "i686-linux-android": ["@rules_rust//rust/platform:i686-linux-android"],
    "i686-pc-windows-msvc": ["@rules_rust//rust/platform:i686-pc-windows-msvc"],
    "i686-unknown-freebsd": ["@rules_rust//rust/platform:i686-unknown-freebsd"],
    "i686-unknown-linux-gnu": ["@rules_rust//rust/platform:i686-unknown-linux-gnu"],
    "powerpc-unknown-linux-gnu": ["@rules_rust//rust/platform:powerpc-unknown-linux-gnu"],
    "riscv32imc-unknown-none-elf": ["@rules_rust//rust/platform:riscv32imc-unknown-none-elf"],
    "riscv64gc-unknown-linux-gnu": ["@rules_rust//rust/platform:riscv64gc-unknown-linux-gnu"],
    "riscv64gc-unknown-none-elf": ["@rules_rust//rust/platform:riscv64gc-unknown-none-elf"],
    "s390x-unknown-linux-gnu": ["@rules_rust//rust/platform:s390x-unknown-linux-gnu"],
    "thumbv7em-none-eabi": ["@rules_rust//rust/platform:thumbv7em-none-eabi"],
    "thumbv8m.main-none-eabi": ["@rules_rust//rust/platform:thumbv8m.main-none-eabi"],
    "wasm32-unknown-emscripten": ["@rules_rust//rust/platform:wasm32-unknown-emscripten"],
    "wasm32-unknown-unknown": ["@rules_rust//rust/platform:wasm32-unknown-unknown"],
    "wasm32-wasip1": ["@rules_rust//rust/platform:wasm32-wasip1"],
    "wasm32-wasip1-threads": ["@rules_rust//rust/platform:wasm32-wasip1-threads"],
    "wasm32-wasip2": ["@rules_rust//rust/platform:wasm32-wasip2"],
    "x86_64-apple-darwin": ["@rules_rust//rust/platform:x86_64-apple-darwin"],
    "x86_64-apple-ios": ["@rules_rust//rust/platform:x86_64-apple-ios"],
    "x86_64-linux-android": ["@rules_rust//rust/platform:x86_64-linux-android"],
    "x86_64-pc-windows-msvc": ["@rules_rust//rust/platform:x86_64-pc-windows-msvc"],
    "x86_64-unknown-freebsd": ["@rules_rust//rust/platform:x86_64-unknown-freebsd"],
    "x86_64-unknown-fuchsia": ["@rules_rust//rust/platform:x86_64-unknown-fuchsia"],
    "x86_64-unknown-linux-gnu": ["@rules_rust//rust/platform:x86_64-unknown-linux-gnu", "@rules_rust//rust/platform:x86_64-unknown-nixos-gnu"],
    "x86_64-unknown-nixos-gnu": ["@rules_rust//rust/platform:x86_64-unknown-nixos-gnu"],
    "x86_64-unknown-none": ["@rules_rust//rust/platform:x86_64-unknown-none"],
    "x86_64-unknown-uefi": ["@rules_rust//rust/platform:x86_64-unknown-uefi"],
}
